import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useAuth } from '../../context/auth';
import { NextPageWithLayout } from './_app';
import { ReactElement } from 'react';
import Layout from '@/components/layout';
import { GetStaticProps, InferGetStaticPropsType } from 'next';
import { Post } from '../../types/post';
import { adminDB } from '../../firebase/sever';
import { doc } from 'firebase/firestore';
import PostItemCard from '@/components/post-item-card';
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';
import { Keyboard, Navigation, Pagination } from 'swiper';
import { ChevronRightIcon, ChevronLeftIcon } from '@heroicons/react/24/outline';

const inter = Inter({ subsets: ['latin'] });

export const getStaticProps: GetStaticProps<{ posts: Post[] }> = async () => {
	const snap = await adminDB
		.collection(`posts`)
		.orderBy('cretedAt', 'desc')
		.limit(20)
		.get();
	const posts = snap.docs.map((doc) => doc.data() as Post);
	return {
		props: {
			posts,
		},
	};
};

const Home: NextPageWithLayout<
	InferGetStaticPropsType<typeof getStaticProps>
> = ({ posts }) => {
	const { user } = useAuth();
	return (
		<div className='container'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<div>
					<div className='relative'>
						<Swiper
							modules={[Navigation, Pagination, Keyboard]}
							loop
							navigation={{
								nextEl: '#next',
								prevEl: '#prev',
							}}
							keyboard
							pagination={{
								el: '#pagination',
								bulletClass:
									'w-2 h-2 rounded-full blok bg-slate-300 cursor-pointer',
								bulletActiveClass: '!bg-blue-500',
								clickable: true,
							}}
							spaceBetween={50}
							slidesPerView={1}>
							{new Array(5).fill(null).map((_, index) => (
								<SwiperSlide key={index}>
									<div className='bg-slate-200 aspect-video grid content-center'>
										<p className='text-3xl text-center font-bold text-blue-500'>
											{index}
										</p>
									</div>
								</SwiperSlide>
							))}
						</Swiper>
						<div
							id='next'
							className='absolute p-4 top-1/2 z-10 right-0 -translate-y-1/2'>
							<ChevronRightIcon className='w-8 h-8 text-slate-400 cursor-pointer' />
						</div>
						<div
							id='prev'
							className='absolute p-4 top-1/2 z-10 -translate-y-1/2'>
							<ChevronLeftIcon className='w-8 h-8 text-slate-400 cursor-pointer' />
						</div>
						<div
							id='pagination'
							className='flex space-x-2 justify-center mt-4'
						/>
					</div>
				</div>

				<h2>最新の記事</h2>
				{posts?.length ? (
					<ul className='space-y-3'>
						{posts?.map((post) => (
							<li key={post.id}>
								<PostItemCard post={post} />
							</li>
						))}
					</ul>
				) : (
					<p>記事がありません</p>
				)}
			</main>
		</div>
	);
};

Home.getLayout = function getLayout(page: ReactElement) {
	return <Layout>{page}</Layout>;
};

export default Home;
